name: DevOps
on: 
  push:
    branches: 
      - main
jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
            registry: registry.hub.docker.com
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       - run: |
          docker build -t registry.hub.docker.com/tuksennitro/abc .
          docker push registry.hub.docker.com/tuksennitro/abc
